sudo: false

language: node_js

node_js:
    - 6
    - 8
    - 10
    - 11

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.npm

before_install:
    - npm config set progress false
    - npm install -g npm

install:
    - npm ci

script:
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG-test" && cd "/tmp/$TRAVIS_REPO_SLUG-test" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const cli = require('${TRAVIS_REPO_SLUG##*/}');"
    - cd "$TRAVIS_BUILD_DIR"

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: CgaEn7aCB/BJHCDVEMakYrBk/DEYw2ZE5bG1YCXdQEBxl5LfXzHXyNj6oPgVrlYw0p+4/JU6T4JAyvZh+3Q9OTlEAtTLLO4KBWD+r4IEGHMDd1fGUD7GR5d3szprb1DfvdIJ5gxh3lGxanKUNbVbuIPP+uHVz0bkcbTplO3cB1tLoSZRELY6CA01X1jW3lpXhuh7dDulCT3XWjGF2Z53BjkS8sNkS1daulzekVWMhKyCdpdpu9B20PD+QsCJIaRy6vO+s/KAB80DbeRn5gtZmfyVAz3LefGGI6upeGIF3ER8cbkXgH99oqksp8qYAnXVIhNV/K8yY3icpJ6JntW/5QlNsJI/LO2xAl0lM40Et6GD2Kc26HrTWbtlToR5tpjeHVq2Ckv4YtnlbCJxE0cQqI82Kxm2dwLGWWg5fOJL7yI/cuAhQ5A7Uqtn/NIB7gtMhYWezPhLnwLH+SSSiuc8j+QQuh8VngJQaCx1sYDnZ1GxmZBR6nY050FfoQ/zb4mNC/bu756XzZjIhbd2L9xn6ypN4/k9OvLe1L41NfQWkviTEXV67CXueTL4l/V26zMtaRmhuR3btP1fEQguZXvnQAAsNn5CX1iBlRn7IaH6qHq9qU89vA3VdQ/hZTiRe8HRNNOEqP09ZKVbozDOG1ER+MRoe+eRkvT6SmdUzfabDzg=
      on:
          node: 10
          repo: whizark/stylelint-cli
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: QJ138SeehoIw1U1UJcCx4Q21JMm+Yb4wGQZwvK6VxpTRmEOStwe4sP1EXuxQWcNX/5jTPheTy1UroMinn1OYOFvWwau7kuw04WgQNBJq/LpPQlLNig/gysRdJRSIv5BmiNfEek85B6v8iQ9QXLtj4goN9XZDZcjGAvc8j77Arq5OqiTPs29IPvWKUhJhnNqduwPYHWOGna+gUKT4CA7Ru4+zYrfpBJR7oqdtiao/KYkuC118x9q+zcIgZO0UL1pcDssz6ddt/Zf7JC/V4S6ikuiHlYS64vtVlTytcQIwhjYIBGBCUxa/YrxBnbw4BOBW0JVVuvGu4WWlatPdknNMVFc9IkkBROkyDS5L4IlzbeMvRaPddcml5rCuhEUJHb5YWa7JOaA8P7JJgcySBsrlTA9Nz2CihnRFbBVUQ6p2p9G0x5KGlp8doBKeoaZfLMDID53ZFMggJ+fstVvKYZZLkPG59m1/2/OCmi7ID3JdcpvvghiqxTMWDl6/LMLVvGrFBBBS071ie1/EHoWMy6xBnyz+cB5f6LihQtlyKkT57Uj3aYm7SMSNhtc78P2B62IBTZz1F4EE3nAJxbsSmmALjX0diq/0QEGTiJbvzpfcNiQf+FsRAIGwqMDDP+2dx5ZhJ7Lc2V19G/E3mjg3bVg3WvBM1ResYKG9c9JuLgGobBU=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
